### ISSUE TITLE
Madnox incompatibility...

### ISSUE THREAD

**Issue by BytEvil** [mikesilvo164/skin.aeon.madnox#32]
Hi. Madnox is incompatible with kodi-git-18.0rc4.r59.g4abe3490217.

> 22:17:39.076 T:140319170402048  NOTICE: ADDON: skin.aeon.madnox version 1.10.1 is incompatible

**Comment by bartolomesoriano** [comment]
@BytEvil, quit Kodi, change the "xbmc.gui" version="5.13.0" line in the skin's addon.xml to "xbmc.gui" version="5.14.0", and then restart Kodi, re-enable the skin, and you should be able to use it normally.  @mikesilvo164 has not pushed that change to Git since not all users are running the latest Leia nightly or RC4.

**Comment by BytEvil** [comment]
@bartolomesoriano, thanks friend! ;) Fixed!
